replicaCount: 1

image:
  repository: kapil772/go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "14451538063"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific